---
- name: configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: copy the License File
  template:
    src: zimbra_license.j2
    dest: /tmp/ZCSLicense.xml

- name: download zimbra installer
  get_url:
    url: https://files.zimbra.com/downloads/10.0.0_GA/zcs-NETWORK-10.0.0_GA_4518.UBUNTU20_64.20230301065514.tgz
    dest: /root

- name: extract zimbra installer
  unarchive:
    remote_src: yes
    src: /root/zcs-NETWORK-10.0.0_GA_4518.UBUNTU20_64.20230301065514.tgz
    dest: /root

- name: configure answer file
  template:
    src: ldap_answers.j2
    dest: /tmp/ldap_answers.txt

- name: configure config file
  template:
    src: ldap_config.j2
    dest: /tmp/ldap_config.txt

- name: run zimbra installer phase 1
  shell: ./install.sh -s -l /tmp/ZCSLicense.xml < /tmp/ldap_answers.txt
  args:
    chdir: /root/zcs-NETWORK-10.0.0_GA_4518.UBUNTU20_64.20230301065514.tgz

- name: run zimbra installer phase 2
  shell: /opt/zimbra/libexec/zmsetup.pl -c /tmp/ldap_config.txt

- name: update ldap system password
  shell: ./zmldappasswd "{{ zimbra_random_chars_2.stdout }}"
  args:
    chdir: /opt/zimbra/bin
  become: yes
  become_user: zimbra

- name: update system passwords
  shell: ./zmldappasswd "{{ item }}" "{{ zimbra_random_chars_2.stdout }}"
  args:
    chdir: /opt/zimbra/bin
  become: yes
  become_user: zimbra
  loop:
    - -a
    - -b
    - -l
    - -n
    - -p
    - -r
